version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: register-redis



  mysql:
    image: mysql:5.7
    container_name: register-mysql
    working_dir: /application
    volumes:
      - ./application:/application
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=register
      - MYSQL_USER=register
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: register-webserver
    working_dir: /application
    volumes:
      - ./application:/application
      - ./support/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - maildev:maildev
    ports:
      - "80:80"
      - "3000:3000"

  php-fpm:
    build: support/docker/php-fpm
    container_name: register-php-fpm
    working_dir: /application
    volumes:
      - ./application:/application

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: register-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=register-mysql
      - PMA_USER=register
      - PMA_PASSWORD=secret
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - mysql


  maildev:
    image: djfarrelly/maildev
    ports:
      - 8282:80